# http://about.travis-ci.org/docs/user/getting-started/
# before_script: "bundle exec rake db:create db:schema:load"
# bundler_args: "--without assets:development:production"
language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
